import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col items-center">
            <header className="flex flex-row container bg-purple-950 py-4 px-8 items-center">
              <h1 className="text-3xl grow">Text App</h1>
              <div className="p-4">
                <SignedIn>
                  <UserButton />
                </SignedIn>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
              </div>
            </header>
            <main className="container border-x-purple-950 border-x-1 ">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
